#!/usr/bin/env python3
"""Verify every generated redirect stub points at a live page.

Walks `docs/site/dist/docs/**/index.html` (the meta-refresh stubs
generated by scripts/generate-redirects.py), extracts each target
URL, and confirms the corresponding file exists in `dist/`.

Exits non-zero on any dead redirect.

Assumes `dist/` was produced by `npm run build`.
"""
from __future__ import annotations

import re
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
DIST = REPO_ROOT / "docs/site/dist"
REDIRECT_ROOT = DIST / "docs"
BASE = "/core-agent"

REFRESH_RE = re.compile(
    r'meta\s+http-equiv="refresh"\s+content="\d+;\s*url=([^"]+)"',
    re.IGNORECASE,
)


def target_file_for(url: str) -> pathlib.Path | None:
    """Map a served URL like /core-agent/concepts/tools/ to the file
    that would satisfy it under dist/."""
    if not url.startswith(BASE):
        return None
    rel = url[len(BASE):].lstrip("/").rstrip("/")
    if not rel:
        return DIST / "index.html"
    return DIST / rel / "index.html"


def main() -> int:
    if not REDIRECT_ROOT.is_dir():
        print(f"error: {REDIRECT_ROOT} not found — run `npm run build` first",
              file=sys.stderr)
        return 2

    stubs = sorted(REDIRECT_ROOT.rglob("index.html"))
    if not stubs:
        print(f"error: no redirect stubs under {REDIRECT_ROOT}", file=sys.stderr)
        return 2

    dead: list[tuple[pathlib.Path, str]] = []
    for stub in stubs:
        html = stub.read_text()
        m = REFRESH_RE.search(html)
        if not m:
            dead.append((stub, "(no meta refresh found)"))
            continue
        target_url = m.group(1)
        target_file = target_file_for(target_url)
        if target_file is None or not target_file.is_file():
            dead.append((stub, f"→ {target_url} (missing)"))

    if dead:
        print(f"FAIL: {len(dead)} of {len(stubs)} redirect(s) dead:")
        for stub, why in dead:
            rel = stub.relative_to(REPO_ROOT)
            print(f"  {rel}  {why}")
        return 1

    print(f"OK: all {len(stubs)} redirect stubs point at live pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
