// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package agent

import (
	"errors"
	"log"
	"strings"
	"sync"
)

// inbox is the per-Agent queue of external messages injected via
// Agent.Inject. Drained pre-turn by Agent.Run and prepended to the
// prompt the model sees on its next turn, sibling to the v1.2.0
// background-agent alert block.
//
// External meaning: not generated by the agent itself or its
// subagents (those are alerts on BackgroundAgentManager). Inbox is
// for harness / orchestrator / external-event input that arrives
// asynchronously while the agent is working.
type inbox struct {
	mu       sync.Mutex
	messages []string
	notify   chan struct{} // 1-buffer signal; non-blocking send on append
	closed   bool
}

// newInbox returns an empty inbox ready to accept Inject calls.
func newInbox() *inbox {
	return &inbox{
		notify: make(chan struct{}, 1),
	}
}

// defaultInboxCap is the soft cap on queued messages before
// drop-oldest kicks in. Matches the v1.2.0 alert channel default
// (256) so consumers see consistent backpressure semantics across
// the two surfaces.
const defaultInboxCap = 256

// ErrInboxClosed is returned by Agent.Inject when the agent's inbox
// has been closed (typically because the agent has been shut down
// via its run context cancelling). Callers that publish messages on
// an unrelated lifecycle (e.g. a stdin scanner) should treat this as
// "stop publishing."
var ErrInboxClosed = errors.New("agent: inbox closed")

// push appends msg to the queue with drop-oldest backpressure when
// the queue grows past defaultInboxCap, and fires notify so a
// waiting Agent.InboxArrived consumer wakes up.
func (q *inbox) push(msg string) error {
	q.mu.Lock()
	if q.closed {
		q.mu.Unlock()
		return ErrInboxClosed
	}
	q.messages = append(q.messages, msg)
	if len(q.messages) > defaultInboxCap {
		// Drop oldest with a logged warning so a stuck producer
		// can't deadlock the agent.
		dropped := q.messages[0]
		q.messages = q.messages[1:]
		log.Printf("agent: inbox cap exceeded, dropped oldest message (head=%q)",
			truncateForLog(dropped))
	}
	q.mu.Unlock()
	// Non-blocking signal. If a notification is already buffered
	// (consumer hasn't drained yet), drop the redundant signal.
	select {
	case q.notify <- struct{}{}:
	default:
	}
	return nil
}

// drain returns all currently-queued messages in arrival order and
// clears the queue. Safe to call concurrently with push.
func (q *inbox) drain() []string {
	q.mu.Lock()
	defer q.mu.Unlock()
	if len(q.messages) == 0 {
		return nil
	}
	out := q.messages
	q.messages = nil
	return out
}

// arrived returns the notification channel a consumer can select on
// to wait for a new push. The channel is shared across consumers;
// only one goroutine should select on it at a time.
func (q *inbox) arrived() <-chan struct{} { return q.notify }

// close marks the inbox closed so subsequent push calls error. Safe
// to call multiple times.
func (q *inbox) close() {
	q.mu.Lock()
	q.closed = true
	q.mu.Unlock()
}

// truncateForLog produces a short single-line preview of msg for
// inclusion in log lines.
func truncateForLog(msg string) string {
	const max = 60
	msg = strings.ReplaceAll(msg, "\n", " ")
	if len(msg) <= max {
		return msg
	}
	return msg[:max-3] + "..."
}

// prependInboxMessages renders queued inbox messages as a stable,
// greppable block and prepends them to prompt. Empty queue returns
// prompt unchanged. Format mirrors the BackgroundAgentManager alert
// block from v1.2.0 so consumer tooling can find both boundaries
// with the same approach.
func prependInboxMessages(prompt string, messages []string) string {
	if len(messages) == 0 {
		return prompt
	}
	return formatInboxForPrompt(messages) + "\n\n---\n\n" + prompt
}

// formatInboxForPrompt renders one message per line under an
// "[Inbox]" header. Stable + greppable.
func formatInboxForPrompt(messages []string) string {
	var b strings.Builder
	b.WriteString("[Inbox]\n")
	for i, m := range messages {
		if i > 0 {
			b.WriteByte('\n')
		}
		b.WriteString("- ")
		b.WriteString(m)
	}
	return b.String()
}

// Inject queues message on the agent's inbox. The next call to
// Agent.Run will drain pending messages, format them as an "[Inbox]"
// block, and prepend the block to the prompt the model sees.
//
// Inject is safe to call concurrently from any goroutine — typical
// usage is a harness goroutine reading from stdin, an HTTP handler,
// or an orchestrator's gRPC stream. Drop-oldest backpressure kicks
// in when the queue exceeds the soft cap (256) so a stuck consumer
// can't deadlock the agent.
//
// Returns ErrInboxClosed once the agent has been shut down; callers
// publishing on an unrelated lifecycle should treat that as "stop."
func (a *Agent) Inject(message string) error {
	if a == nil {
		return errors.New("agent: nil receiver")
	}
	if a.inbox == nil {
		// Defensive: callers should always go through agent.New
		// which constructs a non-nil inbox, but if a consumer
		// hand-constructed an Agent struct (tests in this package
		// do, for example) we don't want to panic.
		return errors.New("agent: inbox not initialised (construct via agent.New)")
	}
	return a.inbox.push(message)
}

// InboxArrived returns a channel that fires when a new message has
// been injected. The harness can use this to decide when to start
// the next turn instead of polling — typical pattern:
//
//	for {
//	    select {
//	    case <-ctx.Done():
//	        return
//	    case <-ag.InboxArrived():
//	        runOneTurn("continue") // inbox prepended automatically
//	    }
//	}
//
// The channel has a 1-buffer signal-style semantics: multiple pushes
// between consumer wake-ups coalesce into one notification (the
// consumer drains the queue and sees them all).
func (a *Agent) InboxArrived() <-chan struct{} {
	if a == nil || a.inbox == nil {
		return nil
	}
	return a.inbox.arrived()
}
