// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package agent

import (
	"errors"
	"log"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"

	"github.com/go-steer/core-agent/pkg/attach"
)

// inboxMessage pairs an inbox message with the prompt_id assigned at
// push time. The prompt_id is the correlation handle threaded through
// the SSE event-stream protocol's `inbox` event (queued / dequeued)
// so an operator-typed prompt can be linked to its downstream
// turn-complete or turn-error. Internal-only — public DrainInbox()
// keeps the legacy []string shape.
type inboxMessage struct {
	id   string
	text string
}

// newPromptID returns a new prompt_id. UUID v7 is sortable by
// creation time, so debugging traces stay ordered without a
// separate timestamp.
func newPromptID() string {
	id, err := uuid.NewV7()
	if err != nil {
		// Fallback to V4 — V7 only fails when the OS clock is
		// unrecoverably broken, which we can't do anything useful
		// about here. A V4 still uniquely identifies the prompt;
		// debugging just loses the time-ordering property.
		return uuid.NewString()
	}
	return id.String()
}

// inbox is the per-Agent queue of external messages injected via
// Agent.Inject. Drained pre-turn by Agent.Run and prepended to the
// prompt the model sees on its next turn, sibling to the v1.2.0
// background-agent alert block.
//
// External meaning: not generated by the agent itself or its
// subagents (those are alerts on BackgroundAgentManager). Inbox is
// for harness / orchestrator / external-event input that arrives
// asynchronously while the agent is working.
type inbox struct {
	mu       sync.Mutex
	messages []inboxMessage
	notify   chan struct{} // 1-buffer signal; non-blocking send on append
	closed   bool
}

// newInbox returns an empty inbox ready to accept Inject calls.
func newInbox() *inbox {
	return &inbox{
		notify: make(chan struct{}, 1),
	}
}

// defaultInboxCap is the soft cap on queued messages before
// drop-oldest kicks in. Matches the v1.2.0 alert channel default
// (256) so consumers see consistent backpressure semantics across
// the two surfaces.
const defaultInboxCap = 256

// ErrInboxClosed is returned by Agent.Inject when the agent's inbox
// has been closed (typically because the agent has been shut down
// via its run context cancelling). Callers that publish messages on
// an unrelated lifecycle (e.g. a stdin scanner) should treat this as
// "stop publishing."
var ErrInboxClosed = errors.New("agent: inbox closed")

// push appends msg to the queue with drop-oldest backpressure when
// the queue grows past defaultInboxCap, and fires notify so a
// waiting Agent.InboxArrived consumer wakes up. Returns the
// prompt_id assigned to the new message so the caller can emit a
// downstream `inbox` event carrying the correlation handle.
func (q *inbox) push(msg string) (string, error) {
	id := newPromptID()
	q.mu.Lock()
	if q.closed {
		q.mu.Unlock()
		return "", ErrInboxClosed
	}
	q.messages = append(q.messages, inboxMessage{id: id, text: msg})
	if len(q.messages) > defaultInboxCap {
		// Drop oldest with a logged warning so a stuck producer
		// can't deadlock the agent.
		dropped := q.messages[0]
		q.messages = q.messages[1:]
		log.Printf("agent: inbox cap exceeded, dropped oldest message (id=%s head=%q)",
			dropped.id, truncateForLog(dropped.text))
	}
	q.mu.Unlock()
	// Non-blocking signal. If a notification is already buffered
	// (consumer hasn't drained yet), drop the redundant signal.
	select {
	case q.notify <- struct{}{}:
	default:
	}
	return id, nil
}

// drain returns all currently-queued messages (with their prompt_ids)
// in arrival order and clears the queue. Safe to call concurrently
// with push. Internal-only — the public Agent.DrainInbox() wraps this
// in drainText for the legacy []string return shape.
func (q *inbox) drain() []inboxMessage {
	q.mu.Lock()
	defer q.mu.Unlock()
	if len(q.messages) == 0 {
		return nil
	}
	out := q.messages
	q.messages = nil
	return out
}

// arrived returns the notification channel a consumer can select on
// to wait for a new push. The channel is shared across consumers;
// only one goroutine should select on it at a time.
func (q *inbox) arrived() <-chan struct{} { return q.notify }

// close marks the inbox closed so subsequent push calls error. Safe
// to call multiple times.
func (q *inbox) close() {
	q.mu.Lock()
	q.closed = true
	q.mu.Unlock()
}

// truncateForLog produces a short single-line preview of msg for
// inclusion in log lines.
func truncateForLog(msg string) string {
	const max = 60
	msg = strings.ReplaceAll(msg, "\n", " ")
	if len(msg) <= max {
		return msg
	}
	return msg[:max-3] + "..."
}

// prependInboxMessages renders queued inbox messages as a stable,
// greppable block and prepends them to prompt. Empty queue returns
// prompt unchanged. Format mirrors the BackgroundAgentManager alert
// block from v1.2.0 so consumer tooling can find both boundaries
// with the same approach.
func prependInboxMessages(prompt string, messages []string) string {
	if len(messages) == 0 {
		return prompt
	}
	return formatInboxForPrompt(messages) + "\n\n---\n\n" + prompt
}

// formatInboxForPrompt renders one message per line under an
// "[Inbox]" header. Stable + greppable.
func formatInboxForPrompt(messages []string) string {
	var b strings.Builder
	b.WriteString("[Inbox]\n")
	for i, m := range messages {
		if i > 0 {
			b.WriteByte('\n')
		}
		b.WriteString("- ")
		b.WriteString(m)
	}
	return b.String()
}

// FormatAutoContinueInbox renders messages with the system-note
// framing used by the TUI's "auto-continue from queued input"
// flow (see docs/operator-input-design.md). The framing tells the
// model these notes arrived while it was working and instructs
// it to either adapt the current task or capture them via the
// `todo` tool — letting the model decide relevance rather than
// guessing in code.
//
// Returns "" when messages is empty (caller should not auto-
// continue in that case). Format intentionally differs from
// formatInboxForPrompt (which prepends to an operator-typed prompt)
// because auto-continue turns have no operator prompt to prepend
// to — the formatted block IS the user message for the new turn.
func FormatAutoContinueInbox(messages []string) string {
	if len(messages) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("[Operator notes added during the previous task]\n")
	for _, m := range messages {
		b.WriteString("- ")
		b.WriteString(m)
		b.WriteByte('\n')
	}
	b.WriteByte('\n')
	b.WriteString("If any of these change the current task, adapt your next step. If they're separate requests, use the `todo` tool to capture them and continue what you were doing.")
	return b.String()
}

// Inject queues message on the agent's inbox. The next call to
// Agent.Run will drain pending messages, format them as an "[Inbox]"
// block, and prepend the block to the prompt the model sees.
//
// Inject is safe to call concurrently from any goroutine — typical
// usage is a harness goroutine reading from stdin, an HTTP handler,
// or an orchestrator's gRPC stream. Drop-oldest backpressure kicks
// in when the queue exceeds the soft cap (256) so a stuck consumer
// can't deadlock the agent.
//
// Emits an `inbox`/queued event on the attach event stream (if one
// is wired) with the assigned prompt_id, so SSE consumers can
// surface the queued state to operators. The same prompt_id flows
// out as the `inbox`/dequeued event when the inbox is drained
// inside Run.
//
// Returns ErrInboxClosed once the agent has been shut down; callers
// publishing on an unrelated lifecycle should treat that as "stop."
func (a *Agent) Inject(message string) error {
	if a == nil {
		return errors.New("agent: nil receiver")
	}
	if a.inbox == nil {
		// Defensive: callers should always go through agent.New
		// which constructs a non-nil inbox, but if a consumer
		// hand-constructed an Agent struct (tests in this package
		// do, for example) we don't want to panic.
		return errors.New("agent: inbox not initialised (construct via agent.New)")
	}
	id, err := a.inbox.push(message)
	if err != nil {
		return err
	}
	a.emit(attach.EventInbox, attach.InboxEvent{
		State:    attach.InboxStateQueued,
		PromptID: id,
		QueuedAt: time.Now().UTC(),
	})
	// Operator input should also pierce any active sleep — the
	// scheduler selects on WakeRequested() alongside its sleep
	// timer, so this lands as an immediate wake.
	a.RequestWake()
	return nil
}

// DrainInbox pulls every currently-queued message off the inbox and
// returns them in arrival order. The queue is emptied as a side
// effect — repeat calls return nil until new messages arrive.
//
// Exposed so harnesses that want to format inbox messages
// differently from the built-in `[Inbox]` block (e.g. the TUI's
// auto-continue flow uses FormatAutoContinueInbox to add system-note
// framing) can pull the messages themselves and pass the formatted
// result to Run as a regular prompt. Run's internal drain then
// finds an empty inbox and is a no-op, so there's no
// double-injection.
//
// Returns nil when no agent or no inbox is wired — both are
// defensive cases for hand-constructed Agent structs in tests.
//
// Emits an `inbox`/dequeued event for each drained message with the
// message's prompt_id, so SSE consumers can correlate the dequeue
// with the earlier queued event.
func (a *Agent) DrainInbox() []string {
	if a == nil || a.inbox == nil {
		return nil
	}
	msgs := a.inbox.drain()
	if len(msgs) == 0 {
		return nil
	}
	for _, m := range msgs {
		a.emit(attach.EventInbox, attach.InboxEvent{
			State:    attach.InboxStateDequeued,
			PromptID: m.id,
		})
	}
	out := make([]string, len(msgs))
	for i, m := range msgs {
		out[i] = m.text
	}
	return out
}

// PendingInboxCount peeks at the inbox without draining it. Useful
// for UI surfaces (TUI queue panel) that need to render the current
// queue length without claiming the messages.
//
// Returns 0 for nil agent / inbox.
func (a *Agent) PendingInboxCount() int {
	if a == nil || a.inbox == nil {
		return 0
	}
	a.inbox.mu.Lock()
	defer a.inbox.mu.Unlock()
	return len(a.inbox.messages)
}

// InboxArrived returns a channel that fires when a new message has
// been injected. The harness can use this to decide when to start
// the next turn instead of polling — typical pattern:
//
//	for {
//	    select {
//	    case <-ctx.Done():
//	        return
//	    case <-ag.InboxArrived():
//	        runOneTurn("continue") // inbox prepended automatically
//	    }
//	}
//
// The channel has a 1-buffer signal-style semantics: multiple pushes
// between consumer wake-ups coalesce into one notification (the
// consumer drains the queue and sees them all).
func (a *Agent) InboxArrived() <-chan struct{} {
	if a == nil || a.inbox == nil {
		return nil
	}
	return a.inbox.arrived()
}
